<?xml version="1.0"?>
<robot name="victoria_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find victoria_description)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find victoria_description)/urdf/wheel.urdf.xacro" />

  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.98740000" />
  <xacro:property name="base_y_size" value="0.57090000" />
  <xacro:property name="base_z_size" value="0.24750000" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.3" />
  <xacro:property name="front_track" value="0.3" />
  <xacro:property name="rear_track" value="0.47" />
  <xacro:property name="wheel_vertical_offset" value="0.075" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1143" />
  <xacro:property name="wheel_radius" value="0.127" />

  <xacro:macro name="victoria_robot">

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://victoria_description/meshes/base_link.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${-wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="33.455" />
        <origin xyz="-0.08748 -0.00085 0.09947" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 -3.1416/2" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
    </gazebo>

    <link name="gps"/>
    <joint name="gps_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="gps" />
    </joint>
    <gazebo reference="gps">
    </gazebo>

    <!-- Victoria wheel macros -->
    <xacro:victoria_wheel wheel_prefix="front_left">
        <origin xyz="${wheelbase} ${front_track/2} ${-wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:victoria_wheel>
    <xacro:victoria_wheel wheel_prefix="front_right">
        <origin xyz="${wheelbase} ${-front_track/2} ${-wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:victoria_wheel>
    <xacro:victoria_wheel wheel_prefix="rear_left">
      <origin xyz="0.0 ${rear_track/2} 0.0" rpy="0 0 0" />
    </xacro:victoria_wheel>
    <xacro:victoria_wheel wheel_prefix="rear_right">
      <origin xyz="0.0 ${-rear_track/2} 0.0" rpy="0 0 0" />
    </xacro:victoria_wheel>

    <xacro:victoria_decorate />

    <xacro:if value="$(arg laser_enabled)">
        <link name="laser_link">
          <collision>
            <origin xyz="0 0 .0585" rpy="0 0 0" />
            <geometry>
              <box size=".1 .108 .117" />
            </geometry>
          </collision>
        </link>

      <joint name="laser_mount_joint" type="fixed">
        <origin xyz="0.27 0.0 0.1"
                rpy="0.0 0.0 0.0" />
        <parent link="base_link" />
        <child link="laser_link" />
      </joint>

    </xacro:if>

    <xacro:if value="$(arg kinect_enabled)">
        <link name="camera_link">
          <collision>
            <origin xyz="0 0 .0585" rpy="0 0 0" />
            <geometry>
              <box size=".1 .108 .117" />
            </geometry>
          </collision>
        </link>

      <joint name="r200_frame_joint" type="fixed">
        <origin xyz="-0.17 -0.04 0.26" rpy="0.0 -0.087 0.0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
      </joint>

    </xacro:if>

  </xacro:macro>

</robot>
